### ISSUE TITLE
Upload or Import via Zip file

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#1033]
**Is your feature request related to a problem? If so, Please describe.**
On unreliable network connections, it's hard to make sure all images in a large image sequence are uploaded	

**Describe the solution you'd like**
Upload a zip with all the same files that would be in an regular import

**Comment by waxlamp** [comment]
@BryonLewis has done a similar thing for MEVA.

**Comment by BryonLewis** [comment]
Just some basic planning for the implementation.

- Add Zip File upload to the Images/Video upload UI.
- Zip file is just a single zip file which contains a flat list of images or a video, and possibly annotations (JSON/CSV)
- How do we handle annotation FPS for zip file, I'm guessing allow the user to specify.
- Using the standard upload allows for the folder initialization and creation
- Determine if I want to include extraction as part of `dive_rpc/postprocess` or a separate endpoint dedicated to zip files?
    - Using `postprocess` already has two contexts (with the skipJobs argument) for video conversion vs the new data after running a pipeline so it may make sense to modify it.
- Either way a girder worker job needs to be kicked off after uploading the zip file.  This job will take the zip file extract all the contents and then upload them to the correspondingly created directory.
- Probably should use the existing `/dive_dataset/validate_files'` within the worker to confirm that there is valid data in the extracted zip file.  If not can fail the worker process and prevent extraction of Zip file data.
- Finally recursive upload of all the files into the folder where the zip resides.  Then possibly marking the zip as extracted so it isn't processed again accidentally in subsequent postprocess or other endpoint runs.

Keep in back of mind the possible future modifications for uploading multiple folders/files in a single zip file.
