### ISSUE TITLE
[BUG] Fix Max width Tooltip display

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#1051]
**Describe the bug**
When using the tooltip hover fix the max-width for large names

**To Reproduce**
Load up data with long type names and turn on the tooltip hovering 

**Expected behavior**
Proper truncation or wrapping for the display area for the tooltip

**Comment by subdavis** [comment]
From slack:

> I'm finding these tooltips actually a little obtrusive.  Instead of "wheverver your mouse enters", how hard would it be to put the tooltip all the way outside the rightmost overlapping box?  The Y coordinate doesn't matter, and I think mouse height makes sense.

> Or, it might look nice just to align the tooltip  with the top right corner of the bounding box containing all overlapping boxes?

**Comment by BryonLewis** [comment]
The location of the tooltip right now is that last mouse position of the user either entering or existing a new box.  Now that I thought about it a bit the outside the furthest away box might not be the best place.  If you had a full frame box meant to denote something about the frame and then sub-boxes for individual objects within that frame this would force the tooltip to the outside of the full frame.
Thoughts?

**Comment by BryonLewis** [comment]
@subdavis, the code is a bit annoying (looping, finding min/max and sorting) but is this behavior better?

https://user-images.githubusercontent.com/61746913/142057542-415fe40e-b35c-45e0-8f05-c063d3c2b884.mp4

**Comment by subdavis** [comment]
Yeah, I think this is a lot better, thanks!

The only difference is that I think it's backwards to what I originally had in mind: that the tooltip would be outside the outermost annotation rather than the innermost.

Depending on exactly how annoying the code is, it may not be worth changing.
