### ISSUE TITLE
[FEATURE] Support for multiple datasets within Zip Uploads

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#1076]
**Is your feature request related to a problem? If so, Please describe.**
The first implementation of zip uploads only works with a single flat dataset.  This would allow  folders to be inside of the zip file and each folder would be created into it's own dataset.  This would enable bulk uploading of multiple datasets without complicating the upload tool further.

**Describe the solution you'd like**

1. Using the existing task in the zip upload the zip file would extract to the temporary location and 'validate_files' would be run on every sub folder.  
2. If the sub folder was determined to be valid it would create a new dataset folder in the root folder and upload the files there.  
3. Once complete it would run `/postprocess` on the root folder to move the zip file into a source folder and then would run `/postprocess` on all of the validated sub folders.
4. Documentation for zip files would also need to be updated to reflect the capability of multiple folders being uploaded

**Additional context**
This would be related to PR #1062 and would be done after the initial version is merged for a single file.

**Comment by waxlamp** [comment]
I'd like to make sure we don't try to do too much in the course of solving this issue. Some kind of behavioral spec before you jump in would be useful, to constrain what we offer here. Put another way, I don't think we should attempt to cover every corner case, etc. We should keep a bit of the ol' UNIX philosophy in our back pocket, for example, and bail out if a byzantine problem begins to develop with a given zip file.

**Comment by subdavis** [comment]
Isn't this done by #1062 @BryonLewis ?

**Comment by BryonLewis** [comment]
Yes, thanks to the update you made to that PR, it was implemented on web.  This can be marked as closed.
