### ISSUE TITLE
Replace stats page with dynamic component based on Mongo data

### ISSUE THREAD

**Issue by waxlamp** [Kitware/dive#1077]
Replace stats page with a dynamically generated version that shows stats for all public, published, owned, and shared datasets that a user has access to. This can be done with a mongo aggregation pipeline.

Solving #306 is a prerequisite; see [discussion](https://github.com/Kitware/dive/issues/306#issuecomment-975619767).

**Comment by waxlamp** [comment]
This issue is at odds with, e.g., #1065, #681, and maybe others. If we're adopting this approach, let's close the issues that are made moot by it.

**Comment by subdavis** [comment]
This issue should be absorbed by #1080, since this is a hasty conclusion about the findings of an investigation we haven't done yet.
