### ISSUE TITLE
[BUG] Transcode error in desktop release

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1109]
![transcode_error_desktop](https://user-images.githubusercontent.com/2353972/148286356-39816b65-c7f1-4ed5-accb-21afab8afffb.png)

**Comment by mattdawkins** [comment]
Current VIAME/DIVE release - video: https://viame.kitware.com/#/viewer/619d2841f71edd12fbc08680

**Comment by BryonLewis** [comment]
https://github.com/Kitware/dive/blob/main/client/platform/desktop/backend/native/linux.ts#L77

This is the problem right here, this needs to be -`c:a copy` I believe.

**Comment by BryonLewis** [comment]
https://github.com/Kitware/dive/blob/main/client/platform/desktop/backend/native/mediaJobs.ts#L79-L85

Additional problem is that VIAME install version doesn't recognize libx264 or `-crf 18` in the command so they need to be removed

**Comment by BryonLewis** [comment]
New build of VIAME fixes this issue by including libx264 codec in ffmpeg.
