### ISSUE TITLE
[FEATURE] Easier import of multiple sequences for single or multi-cam (Desktop)

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1113]
It would be useful to import either a directory of videos, a directory of directories of images, or a directory of directory of multi-cam data (in consistent sub-directory orderings) with a single import as opposed to having to 1 by 1 do this for a directory of say 30 different sequences. Example data for multi-cam forthcoming shortly.

**Comment by subdavis** [comment]
duplicate of #623
