### ISSUE TITLE
Track tails (or trails) in annotator view

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#1114]
Keywords: trails, tails

**Is your feature request related to a problem? If so, Please describe.**
For certain kinds of annotation tasks, like creating and modifying fish tracks, the ability to look at trail lines is useful.  Ability to see gaps in the track, etc.

**Describe the solution you'd like**
See the trails in the annotator.  Maybe just fixed number of frames (forward or backward)? 

**Additional context**
This is complicated and expensive to generate on the client.  Research will need to happen about whether this happens server side or client side.

**Comment by waxlamp** [comment]
@subdavis, by "trails" you mean the head/tail data for the last N frames, is that right?

Does the Mongo storage make this easier? More generally, what makes it hard to generate the trails for a given frame?

**Comment by subdavis** [comment]
No, this has nothing to do with persistence.  This is a client side feature.


It's hard because it makes the runtime complexity bigger.  to render a frame, we've put a huge amount of effort into making lookup-geometry-by-frame-number a very fast operation.  There's a red/black tree and everything.   The result is that, even with hundreds of tracks on screen, each track only does one lookup to render.

Now, to show a tail, you need to do N lookups for previous and future states for every single track.  You can sora pre-computed some of this server-side, but since this is an editor, it's like server-side-rendering: you hydrate client state and then expect it to change as the user does stuff.

That's why I made this difficulty:hard.
