### ISSUE TITLE
Persistent attributes and types between sessions or just attribute export (Desktop)

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1115]
Need a way to more easily share attributes between loaded data with minimal amount of user involvement

**Comment by waxlamp** [comment]
@mattdawkins, could you give an example of what you'd like to be able to do?

**Comment by mattdawkins** [comment]
Whenever a user sets attributes, save them between different video folders so they don't need to re-enter them is my ideal. They should be global by default on desktop not tied to a specific video. That way there's no user activity necessary to re-enter or re-import attributes.

If that is too difficult given the state of girder, then at least the ability to import/export or more readily apply the possible attributes from another video to a new one.

**Comment by subdavis** [comment]
@BryonLewis I think this should be linked to be closed by #1118 right?

**Comment by BryonLewis** [comment]
Closing based on #1118, Allows importing/exporting configuration files (styling, attributes) for desktop and web and interoperability between them.
