### ISSUE TITLE
Make sure default training config is train_detector_default not train_darknet_yolo

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1121]
Half of the time the user just selects the default, darknet_yolo should not be it

**Comment by subdavis** [comment]
I don't understand this issue.   We don't control what defaults do.  That's in the pipeline file from VIAME.

**Comment by subdavis** [comment]
![Screenshot from 2022-01-14 10-46-10](https://user-images.githubusercontent.com/4214172/149543812-52ce80c6-ebac-459f-9c99-4778fd27b92e.png)

The default is currently `train_detector_default`

**Comment by mattdawkins** [comment]
It's not on desktop which also has a YOLO config first, presumably because da comes before de in the alphabet is shown first
