### ISSUE TITLE
Bulk import transcoding failures.

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#1138]
**Describe the bug**
Untriaged bug in prod

**TODO To Reproduce**

**Related data**
* https://viame.kitware.com/girder#job/61f15e3be5fc4ec3c81517df

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

**Comment by BryonLewis** [comment]
Best bet is to make the zip documentation referenced when uploading a zip file.  Error out properly if the media file doesn't contain media (video or images) and in the error provide a link to the documentation for the zip files.

**Comment by BryonLewis** [comment]
When importing if it detects a zip file in pending uploads it will pop open a link directly to the zip file formats:
![image](https://user-images.githubusercontent.com/61746913/151412864-beb4fdae-3f50-4564-a7bf-e0d95ba0e0fb.png)

Then in the extraction also include a reference to the Zip file format as well:
![image](https://user-images.githubusercontent.com/61746913/151413529-af5e5394-3479-4353-aca4-0ab2f39736de.png)
