### ISSUE TITLE
Re-add Statistics Panel in Web Version

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1158]
**Is your feature request related to a problem? If so, Please describe.**

The statistics panel is useful for:

1) People to find if a category of interest that they're interested in is already in the system somewhere
1b) If so where it is
2) Finding out total counts of annotation per different categories
3) Useful for advertisement purposes

**Describe the solution you'd like**

I'd imagine there's several possible levels of progression and different features related to this. 

1) As a first step, making it similar to what it was previously
2) Also not making it cover the global (non-user) training folder, but any dataset in user's public folders as well + anything globally shared
3) Adding in a synonym table that can be modified by admins (fixed initially)

And more longer term things I would see as not that import short term

1) User-specific stats panel based on what data they have access too
2) User uploaded synonym tables, improved specification

**Comment by subdavis** [comment]
Old UI was kinda bad.  I was planning to replace it with a v-data-table just because it's easy.  Possibly using the expansion feature to show the associated datasets: https://vuetifyjs.com/en/components/data-tables/#expandable-rows


The table would be like this, and then you expand the fish row and get links to all 10 of the datasets with fish.

| Type | Number of datasets | Number of annotations |
| Fish | 10 | 3928 |

**Comment by waxlamp** [comment]
@mattdawkins, let us know if you have any objections to this. We're planning to go ahead with it since it's a simple and solid way of readding this feature which can be modified/expanded in the future if needed.

**Comment by mattdawkins** [comment]
>> We should probably not do this. There is so much garbage data in the system that the garbage will overwhelm the actual annotations, and it's unsafe to do when we have no way of currently moderating.

One of the point of this to find if anyone is annotating similar categories on other data though. Searching just "published" data doesn't satisfy that (which isn't our responsibility to review everyone's data, and the term "published" is overloaded here as some people could think that means in research publications so I would advise against using that term at a minimum).
