### ISSUE TITLE
A couple of tracking pipelines are failing on videos

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1167]
**Describe the bug**
A couple pipelines are failing on videos after some recent csv loader modifications

I haven't investigated it in detail, but I think it's likely a default value that some pipelines write out in the image field, "input_list.txt" in all likelihood. Probably either a pipeline config mod to make sure timestamps are printed in that column, or dive just ignoring col 2 values that end in .txt

**To Reproduce**
Run a job similar to https://viame.kitware.com/girder/#job/62095ad0ab16673a66799e37 on videos instead of image lists (and a couple of other add-ons have this issues)

**Comment by waxlamp** [comment]
@mattdawkins, can you look into fixing the pipelines that are putting bad data in that column? That seems like the better fix to me.
