### ISSUE TITLE
Handle Empty Image Names (Column 2)  in VIAME CSV Import

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#1173]
**Describe the bug**
When importing a CSV for an image-sequence where there are no filenames specified in column 2 in the viame csv.  It will error and say that the images are missing from the annotation.

**To Reproduce**
1. Take a working viame CSV for import and delete the values in Column 2 so they are empty.
2. Try to import or load it into the system.

**Expected behavior**
Image ordering is no longer required so it should use the default image sort ordering and not have an error.

**Comment by waxlamp** [comment]
Request came from Rusty.
