### ISSUE TITLE
Option to confirm a classification as correct

### ISSUE THREAD

**Issue by waxlamp** [Kitware/dive#1202]
Need the ability to look at the list of confidence pairs and select one of them as correct (thus boosting its confidence to 1.0).

**Comment by subdavis** [comment]
I think it would be best to put that option here in the Confidence Pairs list of the track editor.

![Screenshot from 2022-03-23 11-26-41](https://user-images.githubusercontent.com/4214172/159735297-c7b2a611-73c9-462c-85fc-611e24c06dc5.png)
