### ISSUE TITLE
Align confirmation checkmarks in the same column for consistency

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1221]
When class names are long and variable, they get misaligned per the below

![screenshot_from_2022-04-08_16-59-29](https://user-images.githubusercontent.com/2353972/162654229-c63e967b-93d4-4cb7-a7a5-30586f4a34d1.png)

**Comment by subdavis** [comment]
Looks like QuadCam.  Any of these should reproduce it: https://viame.kitware.com/#/folder/5e4c2817a0fc86aa0315b1a1

**Comment by BryonLewis** [comment]
disregard, I took some time to create a slightly different dataset which could display the issue.
