### ISSUE TITLE
Infinite Load of (Possibly Malformed, Possibly Not) CSV File

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1228]
**Describe the bug**
Attempting to load the data in //videonas:/other/projects/dive results in an infinite hang (that or waiting 30 minutes wasn't enough)

Also hit similar issue as https://github.com/Kitware/dive/issues/1219 with attempting to empty out the groundtruth file (from auto detection) and it still tries to load it (now I understand that if you press the 'X' next to it it won't try to load it, but I don't think people will know that / not all and some try to manually empty out the groundtruth file path which doesn't work).

**Comment by mattdawkins** [comment]
They are related but I'd still probably say seperate - this is about a specific non-loading CSV whereas 1219 is about DIVE attempting to load the JSON/CSV even if the text field is removed, feel free to differentiate further if you want or merge

**Comment by BryonLewis** [comment]
Looks like it may be an issue in how it loads data from network locations.  Going to have to try a few more things to identify the exact problem.
