### ISSUE TITLE
output information lacking

### ISSUE THREAD

**Issue by filippo-ferrario** [Kitware/dive#1231]
I am reading your guides and I am trying to understand what VIAME and DIVE do, I still did not find a bit of information on what is the output of all these tools. For example, when reading the documentation/tutorial/guide for CoralNet It was clear that at the end of the day I would have had a report file (a csv) with the percent cover of the different categories annotated.

What is/are the output of VIAME? 

It looks super interesting and promising but before going to the extent to set it up, it would be good to understand if it will give me what I need.

**Comment by subdavis** [comment]
Thanks for your interest in VIAME and DIVE.

To give a summary, VIAME is a computer vision software platform useful for training different types of object detectors and full-frame classifiers.  It has a lot of built-in models that we have trained to analyse the types of data our customers have, but if none of those work for you, VIAME lets you train your own.   You can use it via command line, through a web deployment, or with DIVE Desktop.  These different types of deployments have mostly overlapping but some different capabilities.  For example, the VIAME binary bundle installer has special tools for IQR search and rapid model generation, mosaics, and other specialty analysis.

Datasets (either single videos or groups of images) can be annotated as ground-truth for training.  Trained models can be run as “pipelines” to produce a VIAME CSV file, which is the main output of this software.

The output format [is documented here](https://viame.readthedocs.io/en/latest/section_links/detection_file_conversions.html). Typically this file will have bounding box detections and classifications, and possibly track linking.  You can then take these output files and produce summaries using your own scripts or spreadsheet software.  Different groups are generally interested in different information from these files (counts of particular species, density, max count within a single frame, etc).

You can export this file from DIVE by [following these instructions](https://kitware.github.io/dive/Web-Version/#download-or-export-data)

The definitions here may be useful: [https://kitware.github.io/dive/#concepts-and-definitions](https://kitware.github.io/dive/#concepts-and-definitions).

Depending on what your goals are, VIAME/DIVE may or may not be the right tool for you. If you have further questions or would like our help in exploring your use cases, don’t hesitate to let us know and we can answer your questions here or set up a meeting to discuss. Thanks!

**Comment by subdavis** [comment]
Closing, no response from issue reporter.
