### ISSUE TITLE
Type colors not honored on timeline view

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1305]
**Describe the bug**
Changing the colors of the background categories in the attached doesn't change the colored bars in the timeline view which seem to be initialized to random tans/reds most of the time

![Screenshot from 2022-10-31 10-40-29](https://user-images.githubusercontent.com/2353972/199291468-276fb4b2-dc84-48e2-a87f-b8f56f806a72.png)

**Comment by BryonLewis** [comment]
double check this, I believe this can be marked as resolved now.

**Comment by waxlamp** [comment]
@mattdawkins I'm going to close this issue as resolved; if you find it's not fixed on your end, please re-open.
