### ISSUE TITLE
Do not error out when loading a subset of images from those contained in a CSV

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1329]
**Describe the bug**
The attached CSV was computed over 20 frames. When loading against a smaller batch of images, say 5 or just 1 from the set, loading hard errors (with the attatched). An example 1 image set is also attatched and the CSV. This is analogous to a CSV computed over 5 million frames, where we just want to visualize the output on a couple hundred from the CSV. I consider the error a bug not a feature.

![not-helpful](https://user-images.githubusercontent.com/2353972/214761999-7c6c1c08-d79b-4fd2-912b-a8c3d0114650.png)

[example.csv](https://github.com/Kitware/dive/files/10506480/example.csv)

![Set2_DSCN2015 JPG_0](https://user-images.githubusercontent.com/2353972/214761995-3bf9f1fd-dd7a-4b57-a30b-2683c0f59268.png)

(original image name = Set2_DESCN2015.JPG_0.png)

**Comment by BryonLewis** [comment]
I may still have it show a warning because the frames don't align.  The CSV will need to have the proper filenames in every field for this to work then.
I'll have to re-index the found video frames and adjust the input to match properly.
