### ISSUE TITLE
Large resolution mosaic not displaying in viame-web and windows desktop, but is in linux desktop

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#1364]
<img width="891" alt="2" src="https://github.com/Kitware/dive/assets/2353972/6cc2de61-2ab6-48bb-b648-d45be17ecac1">

Linux

<img width="296" alt="Picture1" src="https://github.com/Kitware/dive/assets/2353972/770ea15a-4363-4bd7-bb85-081ae77cee91">

Windows

**Describe the bug**
Above image does not display in windows desktop and web desktop, just linux desktop

**Comment by BryonLewis** [comment]
I believe this is resolved #1366
