### ISSUE TITLE
Filtering by confidence threshold and checked types when downloading VIAME CSV

### ISSUE THREAD

**Issue by smwoodman** [Kitware/dive#1415]
**Describe the bug**
When downloading from DIVE, checking 'export checked types only' excludes the predictions of unchecked types from the downloaded CSV, i.e., it removes that prediction type from being listed in the columns '10-11+: Repeated Species'/'Confidence Pairs or Attributes'. However, it does not exclude a row (i.e., a prediction) if the remaining prediction types are below the provided Confidence Threshold, for either the global/base confidence threshold or individual type thresholds. 

**To Reproduce**
In the public folder https://viame.kitware.com/#/viewer/647e2ce38cab4af0a12656e6:
1) set confidence threshold to '0.86', and select only tracks 'surf' and 'water_open'
2) check 'exclude tracks below confidence threshold' and 'export checked types only'
3) download 'VIAME CSV' (attachment test-images-open+surf-0.86.csv)
4) uncheck 'surf', and download 'VIAME CSV' (attachment test-images-open-0.86)

**Related data**
https://viame.kitware.com/#/viewer/647e2ce38cab4af0a12656e6

**Expected behavior**
Given the steps described above, predictions without a prediction for a checked type above the given confidence threshold(s) would be excluded from the downloaded CSV file, matching the behavior in DIVE where these predictions are not shown in the viewer.

[test-images-open+surf-0.86.csv](https://github.com/Kitware/dive/files/14947900/test-images-open%2Bsurf-0.86.csv)
[test-images-open-0.86.csv](https://github.com/Kitware/dive/files/14947901/test-images-open-0.86.csv)

**Comment by BryonLewis** [comment]
Sorry about the delay in implementation.  But I think I fixed it an will be merging the fix soon.
