### ISSUE TITLE
Web - DIVE configuration JSON file import failing

### ISSUE THREAD

**Issue by m-h-williams** [Kitware/dive#1429]
**Describe the bug**
I am unable to upload a DIVE configuration JSON file along with a image sequence. This was not an issue about a month ago when I was able to load the same configuration file with previous image sequences, but as of yesterday I have not been able to upload the file with a new image sequence. 

**To Reproduce**
1. Go to https://viame.kitware.com/#/viewer/66621e915175a5ecbf14389d
2. Click on Import
3. Import this file https://github.com/zhrandell/Seattle_Aquarium_CCR_analytical_resources/blob/main/data_input/species.json
4. See error: species.json was not a supported file type: too many values to unpack (expected 2)
![image](https://github.com/Kitware/dive/assets/110432901/a7c05793-ea5f-4b5f-8a3f-1f03c2be443d)

**Expected behavior**
I expected the file to populate the Types List (with Show Empty toggled on) displaying the species list and styling configuration used in a previous image sequence folder. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Comment by BryonLewis** [comment]
I apologize for the delay in responding to this.  It was a known bug that I had fixed and just required a redeployment of the server code to be fixed.  You should be able to import the `customTypeStyling` and other data associated with configuration files.

**Comment by m-h-williams** [comment]
Yes, importing the configuration file works now. Thank you for solving this issue!

**Comment by m-h-williams** [comment]
Yes, importing the configuration file works now. Thank you for solving this issue!
