### ISSUE TITLE
When clicking text next to a detection, also highlight it

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#155]

**Comment by BryonLewis** [comment]
Need to see if GeoJS provides a way to know the bounds of a text element,  If not need to create a secondary poly the same size as the text that is written and utilize that in addition to the main box for selecting.

**Comment by BryonLewis** [comment]
Okay so GeoJS doesn't provide a way to do selection on a textFeature by itself.  There is no selection API for it.  So I need to implement a custom way to do text selection.  My idea right now is to try to use the `canvasContext2d.measureText()` function to get the approximate coordinates of the area and then make sure it is relevant to the geoJS position and try to use that to determine if the user is clicking.  It is overly complicated but could work for this feature.

**Comment by subdavis** [comment]
Motion to close this as wontfix.  GeoJS hacks are :-1:

**Comment by BryonLewis** [comment]
motion granted

**Comment by BryonLewis** [comment]
This is blocked until GeoJS has the ability to click on text layer items and return the ID of the item clicked on.
