### ISSUE TITLE
Once user settings are implemented add Delete confirmation Setting

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#190]
Once we have user based settings add in an override for Deletion confirmation.  It is defaulted to off, but the user can enable it.

**Comment by subdavis** [comment]
Elevating priority since we've gotten feedback from internal and external users.

**Comment by subdavis** [comment]
This is too important to be blocked on implementing user settings.  100% of the feedback we have on this is that a confirmation dialog is needed.  We can just shove the toggle somewhere until we get a permanent home for it.

**Comment by BryonLewis** [comment]
I think to get this in right now we put a new category under the "Track Settings".  There exists "New Track Settings" we add "Deletion" category with the prompt option.  This setting goes into localStorage like the newTrack settings for now.

On first deletion without any localStorage setting it will prompt the user if they want to confirm each deletion and tell them where the setting is to change it.
