### ISSUE TITLE
Update documentation / wiki images automatically via integration testing 

### ISSUE THREAD

**Issue by aashish24** [Kitware/dive#222]

**Comment by aashish24** [comment]
Related to #144

**Comment by BryonLewis** [comment]
Ideally we would want a way to test the data without the backend, or the ability to spin up a backend server and some test data for testing.  For right now though we should be able to utilize the Viame.kitware.com web server with puppeteer to grab specific images.
Furthermore if we do this inside of the wiki repository we could make it even smarter.  We could store a result of the images and compare them with currently tested images.  If the images are signficantly different we could search through the wiki files and find any references and note to the user that they should update those wiki entries to reflect the newer images.

This would mean we run the script to create the test images and get back a list of items that have changed as well as where in the Wiki those images are referenced.

**Comment by BryonLewis** [comment]
I've been messing around with playwright recently for UI automation.  I've made some basic changes to it and it may be a candidate for creation of this tests as well updating the documentation images.

https://user-images.githubusercontent.com/61746913/110491435-47676780-80bf-11eb-825f-765df43215ee.mp4

**Comment by waxlamp** [comment]
Do we really need this? I usually think of documentation as an activity where automation doesn't help very much or can even hurt. I nominate this issue for closing, but if someone can explain the rationale for tackling this instead, I'm listening.
