### ISSUE TITLE
Allow specification of which/how many GPUs should be used for detection/training

### ISSUE THREAD

**Issue by AlmightyYakob** [Kitware/dive#224]
At first this can just be configurable in girder itself (not exposed to the user). This should allow you to assign specific GPUs to the tasks of training/detection.

**Comment by aashish24** [comment]
There might be no support for it on the backend.

**Comment by mattdawkins** [comment]
e.g.

export CUDA_VISIBLE_DEVICES=0
export CUDA_VISIBLE_DEVICES=0,1
export CUDA_VISIBLE_DEVICES=1

etc...

**Comment by subdavis** [comment]
This was done a long time ago.
