### ISSUE TITLE
More verbose pipeline errors in job panel

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#227]
When a pipeline error occurs (attached) there's no information for end-users (who should I contact?) or developers (what was the error?). It would be helpful to have the log be viewable for developers, but also for end users something along of "contact viame-web@kitware.com or your local sys-admin" or the like when errors occur.

<img width="1250" alt="tmp" src="https://user-images.githubusercontent.com/2353972/88204620-896b9800-cc19-11ea-81c3-b4bbf63d8401.png">

**Comment by subdavis** [comment]
I'm tempted to bring this into the bugfix milestone, but I think it's more of a feature task. I'd like to replace this job list with the job list from the desktop, but coming up with the common interface will be nontrivial. 

This is an important issue, though.

**Comment by subdavis** [comment]
Will add contact information and a repeat of the downtime message somewhere on the jobs page.

**Comment by subdavis** [comment]
Links to logs were added.
