### ISSUE TITLE
Drop "file browser" interface

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#252]
This is just my opinion, someone else should weigh in:

We should drop the whole file manager style interface because users find it confusing and overly complicated.  All they really want is a flat list of their projects (which we represent internally as folders).  We could force all users to upload into their `Private` folder and hide all the folder details, still provide the sharing settings (public/private, share with individual users, etc).  Then they'd just have a flat list of searchable projects. 

This is how every other project that uses girder (that I'm aware of) works: nobody actually exposes the file manager functionality to users.

All the media, annotation files, auxillary, everything would be hidden.  There would be a list of cards or a data table with a single entry for each project, a launch button, and that's it.

**Comment by f4str** [comment]
This issue may no longer be relevant as mentioned in https://github.com/Kitware/dive/pull/487#issuecomment-754827212

@subdavis can you verify?

**Comment by subdavis** [comment]
Agree, this is a wontfix for now.
