### ISSUE TITLE
Add method to get total object counts per category in a folder (that pass filter threshold)

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#283]

**Comment by subdavis** [comment]
What is this for?  Who will be using it?

**Comment by mattdawkins** [comment]
Counting instances of object categories, e.g. there are 10 people total in this dataset, or 100 juvenile seals

Anyone with counting problems would use it

**Comment by subdavis** [comment]
Blocked on #306

**Comment by waxlamp** [comment]
@subdavis do we need more info on this issue? Now that #306 is in process, we can at least triage this issue.

**Comment by subdavis** [comment]
I'm going to let #1080 eat this issue.  Closing as duplicate.
