### ISSUE TITLE
COCO support

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#285]
Import/export for https://cocodataset.org/#format-data

**Comment by subdavis** [comment]
Should implement KWCoco https://github.com/Kitware/kwcoco

**Comment by aashish24** [comment]
fyi we also need to implement support for kwcoco for the RGD, not sure if the code can be shared though

**Comment by subdavis** [comment]
I think the shared code is probably the library Jon Crall maintains at https://github.com/Kitware/kwcoco

I expect that both DIVE and RGD will be able to import and use that.

**Comment by aashish24** [comment]
> I think the shared code is probably the library Jon Crall maintains at https://github.com/Kitware/kwcoco
> 
> I expect that both DIVE and RGD will be able to import and use that.

Sure that makes sense. If needed  feel free to reach out to Bane S. if you two would like to discuss it further

**Comment by russelldj** [comment]
I just wanted to chime in to say that I'm quite interested in this feature. It would be very helpful to allow more interoperability with the outputs of general deep learning tools and specifically those maintained by Jon, such as `netharn/bioharn`. I just, yet again, hit an issue where I can't easily visualize the result of a model I ran. Improving the `kwcoco` utility scripts that convert from `viame.csv` <-> `kwcoco` could be an acceptable workaround, but is annoying long term.
