### ISSUE TITLE
VIAME-Web processing docker container dashboard requires manual deletion of container every build

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#288]

**Comment by subdavis** [comment]
I don't understand this issue.  I'm not sure what the dashboard is, or where/when this is happening.  

What's the desired behavior?

**Comment by mattdawkins** [comment]
This is a note for taylor and I, we have a dashboard machine that builds the pipelines but it requires manual deletion of old docker containers when it happens

**Comment by waxlamp** [comment]
@mattdawkins, since this is not an issue to be fixed in DIVE, I'm going to close. Please make sure to capture your note and move it to a more suitable location.
