### ISSUE TITLE
[BUG] Decimals with non-zero values in some VIAME csv outputs when the input had no decimals and just integer boxes

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#295]
**Describe the bug**

**To Reproduce**

**Related data**
Is there a dataset on [viame.kitware.com](https://viame.kitware.com) that illustrates this bug well?  Please link it here.

**Expected behavior**

**Desktop (please complete the following information):**

**Additional context**

**Comment by BryonLewis** [comment]
On bounding boxes we added the rounding capability so I believe that this hasn't been seen in quite some time unless a better example can be provided.

**Comment by waxlamp** [comment]
> On bounding boxes we added the rounding capability so I believe that this hasn't been seen in quite some time unless a better example can be provided.

In light of this, I'm closing the issue. Please re-open with extra information if this is still valid.
