### ISSUE TITLE
[FEATURE] [Housekeeping] Move track data into Mongo

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#306]
Right now, we store track json as a flat file in the asset store.

While it's quick to stream over the network, it's slow for update/delete operations because you have to load the whole thing into memory and parse it first.

**Describe the solution you'd like**
What if we moved the track JSON into mongo, either through a custom Girder Model or directly in folder metadata.

This would also enable us to do much more powerful search/aggregation on the track data.  We could easily generate count summaries, lengths, and other statistics of the sort Matt has asked for.

**Describe alternatives you've considered**
We could keep doing what we're doing.  I don't care so much about the performance optimization, but I wonder if we could have better confidence in the integrity of the data if it lived in Mongo.

**Comment by AlmightyYakob** [comment]
I think this is a good idea. One thing to keep in mind is that currently we store detections redundantly, keeping old files but only using the latest one. I think we'd want to preserve that behavior, to guard against pipelines not producing the desired results, or other possibilities. For that reason I think it makes sense to store them as a custom girder model.

**Comment by subdavis** [comment]
> I think we'd want to preserve that behavior, to guard against pipelines not producing the desired results, or other possibilities. For that reason I think it makes sense to store them as a custom girder model.

I agree.  There are a lot of ways we could implement this, some with more redundancy than others.    I think a nice balance would be to only ever create (never update) Track entities.  Updates create a new entity with the same trackID and mark the old one as outdated.  Deletes simply mark the old one outdated.

This would make it possible to snapshot the dataset state at any point in time with fairly low redundancy.

**Comment by subdavis** [comment]
# Tracks in MongoDB Discussion

## Motivation

This change hopes to resolve some long-outstanding technical debt we took on by modeling domain objects as girder items.

* Poor write performance: for large data, save operations could take many seconds, up to 10+ seconds.  Saves should now be near instant.
* Inaccessible revision history.  We have advertised the ability to review and restore revision history, but it always required emailing us.  Bryon and I have spent enough time manually modifying user's revision history for them that this makes sense to expose to users.
* No audit.  Users could save data, but didn't have a record of where that data came from, who made it, or what changed.  We will now be able to show revision log with author, change summary, source (user save?  pipeline run?), and time.  This should help adoption by increasing transparency and user trust.
* Poor data discovery.  Matt has often talked about wanting to make the data available in the system more discoverable, letting users see more information about the sorts of data they could use in training.  In addition to the shared with me page, we should not be able to show users every label in every dataset they can access.

## Strategy

In order to do this carefully and deliberately, here's a proposed plan for getting this done.

* Create a new branch `develop-mongo-tracks` as a long-running feature branch.
* Make pull requests into this feature branch one at a time, considering each PR on its own.  This will hopefully reduce the fatigue of reviewing large PRs

### Pull requests

- [ ] #1066 (large)
- [ ] #1067 (medium)
- [ ] #1068 (small)
- [ ] #1069 (small)
- [ ] #1070 (small)
- [ ] #1071 (only deletions)

# Other outstanding work

* Replace stats page with a dynamically generated version that shows stats for all public, published, owned, and shared datasets that a user has access to.  This can be done with a mongo aggregation pipeline.
* Add new UI for access to revision history in UI
* Add new UI for issuing a revision rollback
* Re-evaluate report generation needs based on new storage backend.

# Interaction with new Group feature

Related to #1045 and #850, I think doing the group part first will simplify this feature on the data management side, but these changes shouldn't impact each other much.  They could be done in either order.  

# Related issues

Once we're done, this change will either resolve or make progress toward resolving:

* #839 
* #283
* #331 
* #681
* #691 
* #926 (maybe)
* #942

**Comment by waxlamp** [comment]
I think this approach is sound. I'd like to log any drawbacks or difficulties of this approach so we can make good decisions about moving forward.

> # Other outstanding work
> * Replace stats page with a dynamically generated version that shows stats for all public, published, owned, and shared datasets that a user has access to.  This can be done with a mongo aggregation pipeline.
> * Add new UI for access to revision history in UI
> * Add new UI for issuing a revision rollback
> * Re-evaluate report generation needs based on new storage backend.

I filed #1077, #1078, #1079, and #1080 to track these. Feel free to update the tags on those (including creating a new tag to track this Mongo update effort on the whole).
