### ISSUE TITLE
[FEATURE] Allow arbitrary folder hierarchy for no-copy imports

### ISSUE THREAD

**Issue by AlmightyYakob** [Kitware/dive#309]
**Is your feature request related to a problem? If so, Please describe.**
When importing data from the server, the folder hierarchy often doesn't match what we expect in Viame-Web, and so data wrangling would have to occur for the import to succeed. Furthermore, when it comes to exporting this data, it could be a hassle for customers to have to wrangle the data back into the format they need, which may be much more difficult as the organization would be lost, since it's now a flat list of files.

**Describe the solution you'd like**
The annotation files should contain the relative paths to the images. If we read this file first and resolve the relative paths to the data, we should be able to preserve the folder hierarchy.

**Comment by waxlamp** [comment]
@BryonLewis is this issue solved by the import/export work you did?

**Comment by BryonLewis** [comment]
This is related to the server mounting data and not a UX experience with the user.  I've never used the no-copy import feature when launching the server.  I also don't know when was the last time we used no-copy imports.
@subdavis  may be able to give a better response.

**Comment by subdavis** [comment]
This issue should be closed.    We haven't encountered this as an issue in a long time.   The current no-copy import requirements that folders be structured in a certain way is currently fine for our needs.

We have not had to ever walk a customer through the process.  If we did, I assume it would be painful, but we haven't.
