### ISSUE TITLE
[FEATURE] Remove use of girder transforms

### ISSUE THREAD

**Issue by AlmightyYakob** [Kitware/dive#317]
Original comment https://github.com/VIAME/VIAME-Web/pull/315#discussion_r482963689.

**Describe the solution you'd like**
These transforms can always be replaced with a call to a girder client [download](https://girder.readthedocs.io/en/stable/python-client.html#girder_client.GirderClient.downloadFolderRecursive) function in the task itself. This would both cause less confusion when reading the code, as well as allow for finer control of downloaded files/folder. Since these transforms are performed entirely before the task is run, sometimes the resulting behavior is inefficient.

**Comment by subdavis** [comment]
This has been done
