### ISSUE TITLE
[BUG] GeoJS polygon layer must draw twice

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#365]
Two calls to `draw()` are necessary for the polygonLayer  to get it to pick up style functions applied to the layer.  This shouldn't happen, and we aren't sure what caused it.  The bug was discovered on #355 where an extra reactivity loop update was making the second call, hiding the bug.  That change eliminated the extra loop, causing this to appear.

>  It's always the second render loop.  If you disable the default updateLayers in LayerManager it won't draw anything in the beginning, on first update only text, then the second update it will do rects.  So that eliminates any weird timing issues with loading the data.

> The Polygon webGL render has RGB data for the color of lines.  Looks like I can grab out of the renderer in there a color that corresponds with the type color.

> I've traced the issue to createStyle  -- basically when the app loads, the rectangles don't get drawn.  If you touch basically anything, they appear.  checkbox, visibility controls, even clicking the right region of the screen to trigger selection.

**Comment by waxlamp** [comment]
@subdavis, is this still valid?

If yes, could we fix this in the short term by just calling `draw()` twice, opening a new issue for the performance implications thereof? And also: is this a DIVE bug or a GeoJS bug?

**Comment by subdavis** [comment]
We currently just call draw twice. Not sure what the status of the bug is in GeoJS.  Not sure if it rises to the level of importance to investigate.

**Comment by waxlamp** [comment]
I'd consider this issue closed. Perhaps we should make sure there's a comment explaining why we call `draw()` twice, and perhaps we should ask David Manthey for his insight. But as far as actionability here, I think we're done. Re-open if I'm wrong.
