### ISSUE TITLE
[BUG] Previous detections are moved before a pipeline begins

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#375]
**Describe the bug**
It seems as though previous/existing detections are moved to the auxiliary folder before the pipeline begins.  This means that if the pipeline fails or is cancelled there would be no current detections for the folder.  So a failure would remove your current data.

**To Reproduce**
1. Load some Data into the server (make it small)
1. Do a simple generic detection path on it
1. Start another pipeline that either fails, or while it is running cancel it
1. Reload and your previous detections are completely gone. (Make sure you do a hard reset (CTRL+R or CTRL+click reload) because it seems like it caches the track data)

**Related data**
https://github.com/VIAME/VIAME-Web/blob/master/server/viame_server/viame.py#L71
You can see that the data is moved before the pipeline completes.

**Expected behavior**
The old detection file should only be removed upon successful completion of a pipeline and a new csv or track data being loaded.  Might be necessary to place it in the /postprocessing so that if there are multiple .json/.csv files it moves ones that aren't set as the current detection data.

**Comment by BryonLewis** [comment]
Looking closer at the code in `saveTracks` we do a call to `move_existing_result_to_auxiliary_folder` as well.  So if we simply remove the one instance it keeps the detection item in the main folder and will move it once `saveTracks` is called indicating that there is a successful new CSV file in the folder. 

I think this probably the more intended behavior.  The pipelines being run are flaky locally so I'll have to try to testing with some smaller stuff.

**Comment by AlmightyYakob** [comment]
What impact does moving a detection to `auxiliary` have? Is it a problem when exporting detections? Calling `move_existing_result_to_auxiliary_folder` shouldn't affect whether it can be loaded or not, since the `detection` metadata is still present on the item.

**Comment by BryonLewis** [comment]
You are correct and this was an amazing mismatch of:
1. The secondary pipeline I was running would actually produce a 0 Byte CSV files
1. Cancelling the job using admin tools doesn't actually stop the job from running and it still generates that empty csv file.
1. Then any subsequent runs of failing pipelines will move the current track file to the auxiliary and the root looks like it has no track file associated with it although it is just associated with an empty file in auxiliary.

I still do believe that we should keep the most up to date detection file in the root and not in auxiliary for exporting.  Also am now wondering if we should display to the user the difference between **No** track/detection file and an **Empty** track/detection file.  I was confused because I didn't manually go into the auxiliary folder to look at it.

**Comment by subdavis** [comment]
@BryonLewis I don't think this is still a problem.  

Petition to close?
