### ISSUE TITLE
[FEATURE] Warn user if trained pipeline with same name already exists, handle overwriting, etc.

### ISSUE THREAD

**Issue by AlmightyYakob** [Kitware/dive#392]
Right now, the case where a user tries to train a pipeline with the same name as an existing one isn't handled. This may be mostly addressed if we decide to switch how we store trained pipelines, as mentioned in #389. In that case, we could just delete the original folder, remove the relevant metadata, or only return the latest folder (like we do now when retrieving a folder's detections).

Regardless of backend changes, there should still be a dialog in the UI to inform the user that they would be overwriting an existing pipeline.

**Comment by waxlamp** [comment]
Closing as dupe of #938.
