### ISSUE TITLE
[BUG]False Succeeding on empty datsets

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#396]
**Describe the bug**
Doing a training on an empty dataset succeeds in principle
**To Reproduce**
1. Upload short annotation data and ran training using the default netharn
1. After completion it produced a generated pipeline that I could run on data
1. I ran that pipeline on the same folder (IMPORTANT: it returned no detections/tracks)
1. Then started an SVM training on the same dataset
1. It successfully completed with a green checkmark in jobs
1. There was no corresponding trained pipeline in the pipeline menu
1. There was also nothing new in the trained folder

**Related data**
I used a really small subset of EHU (like 20-30 frames) with a single simple track.  When it did train the svm afterwards it did produce some reasonable results.

**Expected behavior**
Probably should error out in some better way if you happen to train on a dataset with no detections/tracks in it.  This was entirely my mistake because I didn't remember to load up new detections in between but it still feels a bit weird having it say the job was a success but having no trained pipeline afterwards.

**Additional context**

**Comment by subdavis** [comment]
I don't think we can do anything about this from our side.  This is up to VIAME/VIAME to handle properly.

**Comment by subdavis** [comment]
DIVE side behavior is correct.  Problems with exit code must be resolved upstream.
