### ISSUE TITLE
[FEATURE] Lock camera on selected track

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#431]
**Is your feature request related to a problem? If so, Please describe.**
Matt and I talked about implementing the locked camera view from the WAMI viewer version in this.  It allows the camera to center the track through multiple frames and when selecting new tracks it will move the camera to center it on the new track.

The main problem is that in large datasets it is sometimes difficult to determine where tracks are located, this will enable this to work.

**Describe the solution you'd like**
Toggle for locking the camera next to the reset camera button.  It will allow the user to toggle the lock on to automatically jump to tracks instead of hunting for them.  I think I may want to indicate it is locked a little more than just the standard unlock/locked icon.  A color change will probably help make it a little more noticeable.

**Describe alternatives you've considered**
Keyboard shortcut to center the camera on the selected track could be added as well that way the user could quickly center it without remaining locked.

**Additional context**
Example of it working in the wami viewer:
![lockedAnnotation](https://user-images.githubusercontent.com/61746913/98682105-8663f700-2331-11eb-80bc-e1ca893dad85.gif)

**Comment by subdavis** [comment]
This sounds like it would involve changes in much of the guts of the annotation viewer.

What VIAME Web customer wants this?  Can we form a user story about them?  Any example dataset where this would apply?  WAMI viewer is useful for demonstrating the concept, but not relevant here.

**Comment by BryonLewis** [comment]
This was a request from Matt.  Specific to Seal or large image datasets with small tracks.  Mostly people having difficulties identifying where tracks are in these 5k or larger images.  I'll ask Matt for the dataset he was using where he was having this specific issue.

The change would require hooking into the annotator.js from inside the LayerManager, a selectedTrack knows it's bounds and center point so you just forward that to the annotator.js and if the setting is on it moves the camera.  Similar to how we already do this for the  icons in the editing modes and the editHandles.

**Comment by subdavis** [comment]
this was done a long time ago.
