### ISSUE TITLE
[Housekeeping] Data schema for attributes and other dataset meta

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#469]
This issue is to discuss data persistence for attribute data and custom styling data.

# Option 1: All 1 json file

Unify all this data in the track json file, such that a single file is compatible with viame web and dive.

* On VIAME Web, the data would actually go in folder metadata for faster access/update, so that the entire track json doesn't need to be read and deserialized just to get the header
* At export time, this meta would be added to the json
* At import time, it would be read out of the json and kept in folder meta.

This would require changing the track json schema to look something like this:

```
{
  "schema_version": 1.0,
  "attributes": {},
  "customStyle": {},
  "tracks": { /* current track schema */ }
}
```

### Considerations

* This would require some work to migrate to.  We might want to run a migration job to iterate over existing datasets and convert, or we might want to just lazy-convert as datasets are opened and saved in the editor.  
* This has a few upsides in that it helps us solve some other outstanding issues.  #454 (manifest) could go in this file.  FPS and other dataset meta could also be stored here, which is an outstanding problem in desktop.

# Option 2: a separate file

Similar to option 1 where data "lives" in folder metadata, but at export time, separate files are generated for download.  

* This could potentially make configuration easier to "share" between datasets on desktop, IF your sharing method involves copy/pasting a file from one dataset folder to another.  If instead your sharing method is managed through the GUI i.e. "Import attributes from external dataset X" then it doesn't really make a difference.  
* If users want to edit this file directly, it might be nice to have a clutter-free single file you can edit without worrying about annotations.
* Experience with the KPF, KW18 file formats has proved quite unpleasant on other projects, and several D&Aers have come to the conclusion that the multi-file format is at least partly to blame.
* Importantly, the distinction between this and KPF is that these files would be totally independent of one another. There are not cross-file dependencies, so you can parse one without the other, and this doesn't change the context.

# Hybrid/incremental option:

If you really want to break attributes out, maybe allow a copy-import override where it gets "written into" the main file when you do the import.

* So I can, for example, email my attributes file to a colleague, and they can import it, but ti's actually just written into the track json.
* Likewise, there could be a button in the UI to generate this separate attributes file, where it gets pulled out of track json and downloaded so you can edit/share it.

-------------------

@subdavis thinks that, whether we do 1 or two files, the schema change in option 1 will be necessary for unrelated reasons.  Relying on filename as a convention and not being able to version our schema has been a painfully dumb choice on my part.  I'd prefer option 1 to start, then add hybrid if users want it.   I have a strong gut feeling that users would prefer to just manage their attrs through the UI and don't want to deal with our files at all.

Open to other perspectives, of course.

**Comment by subdavis** [comment]
Tagging @BryonLewis for thoughts.

**Comment by BryonLewis** [comment]
I like the idea of the hybrid approach where you can output the attributes/styles and import them as well.  I have a feeling once we have templated styles and attributes, someone is going to want to share them between web and VIAME-Dive and not necessarily the data that is associated with the template.  The other option is that they have to import the data and then use the internal sharing mechanism for their platform (desktop/web).  Although this could be nasty with stuff like uploading the whole dataset to the web and downloading the whole dataset to a desktop just to get the attributes and styles.

**Comment by subdavis** [comment]
New idea, given the constraint that we cannot expect a user to have a particular directory structure:

## Project directory style

Instead of having media co-located with annotations, switch to a fixed user-project-directory location.

For example: `/home/VIAME_DIVE`

```
~$ ls -T VIAME_DIVE/
VIAME_DIVE
├── Projects
│  ├── Ehu_1
│  │  ├── auxiliary
│  │  ├── meta.json
│  │  └── results.json
│  └── whatever.mp4_1
│     ├── auxiliary
│     ├── meta.json
│     └── results.json
└── TrainedPipelines
   └── Ehu_1_training_config_name_timestamp
```

This sorta goes back on the unified single file, but since the requirement that sibling videos must be able to be opened as separate datasets breaks any ability of data/annotation co-location, it also breaks any ability for media/annotation portability.

In other words, it's no longer possible to take a DIVE Desktop directory and upload it to VIAME web, and it's not possible to drag your project into a thumb drive or google drive to share it, so making choices in service of portability may no longer be useful.  

Regardless of how many json files there are, there will need to be a new concept of import/export instead of just "open".  Unfortunately, if a user moves their media (images/video) there will have to be some error handling to prompt the user to locate the old file after a move.  

There are also risks to confusing/frustrating users.

For example, imagine they "import" a directory containing a video and a single csv.   The CSV will be moved into the project directory as a json, but what to do with the exiting CSV?  If we leave it where it was, the user may try to edit it by hand and get frustrated when their changes don't show up in the client.  

Probably the new unit of portability will eventually have to be a .zip containing the media, annotations, etc.

**Comment by subdavis** [comment]
## More thoughts.

I want to more rigorously separate the code that runs in the renderer process and the code that runs in the background(main) process.  Thinking about how to write this such that both renderer and background are able to load dataset data is making me get sloppy.

## Proposal

* Disable node integration.  Add a REST api for loading JSON from disk to make the dekstop client more similar to web.
* Only perform filesystem operations in main thread.

## File separation.

I'm no longer convinced that migrating the old track schema is worth doing immediately.  Seems easier to just make a new `meta.json` file with all the metadata. Portability is no longer a concern, and this format will actually be easier to export from web anyway (only have to encode `folder.meta` as a file, instead of modifying a larger json file in the request thread).

**Comment by subdavis** [comment]
This is pretty well out of date.
