### ISSUE TITLE
[BUG] Desktop - flickering in image display when making lots of annotation fast

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#495]
When I go into continuous mode and make lots of annotations fast the screen flickers to black (didn't capture on tape) but when I do something like the below

![flicker](https://user-images.githubusercontent.com/2353972/102090438-78e7d400-3deb-11eb-9d7d-4af8945f0d28.png)

**Comment by subdavis** [comment]
Tried in both web and desktop (windows).

1. From empty image sequence
2. Configure track creation settings: Detection, Continuous.
3. Rapidly drag small boxes quickly.

Cannot reproduce.

**Comment by waxlamp** [comment]
> Cannot reproduce.

Closing. Re-open if there's a repro.
