### ISSUE TITLE
[BUG] Normalize timestamps in downloaded CSV with those in KWIVER/VIAME pipelines

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#497]
Video timestamps are typically provided as:

XX:YY:ZZ.MS (where MS has at least 2 digits)

not

YY:ZZ.MS (where MS has 1 digit)

**Comment by subdavis** [comment]
Does this preclude videos lasting longer than 59.99?

**Comment by subdavis** [comment]
Also, It seems KWIVER pipelines have stopped reporting timestamps altogether. In the column where timestamp should be, there's just "input_list.txt"

**Comment by subdavis** [comment]
Also, I checked https://viame.readthedocs.io/en/latest/section_links/detection_file_conversions.html and didn't see  anything mentioning either timestamp format or `input_list.txt`

**Comment by subdavis** [comment]
Appears to be resolved.
