### ISSUE TITLE
[FEATURE] Create taxonomic view page

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#540]
This page which show all object categories people have annotated in the system (or others manually entered) and let people organize them into a hierarchy of labels, defining child/parent relationships or label synonyms

**Comment by mattdawkins** [comment]
Maybe this would also let users click a specific category, and it would show links to all public datasets containing this category

**Comment by subdavis** [comment]
> This page which show all object categories people have annotated in the system (or others manually entered) 

This is doable but needs refinement.  Could you add some more specific details about what you want to see and why?

* When users view this page, what goal are they trying to accomplish?  Are they searching for data they already have?  Is this overview helpful with training somehow?

>  and let people organize them into a hierarchy of labels, defining child/parent relationships or label synonyms

This is fairly separate, needs discussion, and should probably be broken into another issue
