### ISSUE TITLE
[BUG] Increase ability to pan left, right, up and down

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#542]
There seems to be a hard blocker on not being able to pan left and right a certain amount (an invisible wall). In a few circumstances this has prevented from centering on targets towards the edge of the image (it is impossible to get something in the center of the FOV near the boundary at a few zoom levels)

**Comment by subdavis** [comment]
I don't understand this issue. DIVE will allow a large margin around the media element now.


* Please see the video below and provide some more info about what is not working or unexpected.
* Is the amount of space insufficient?  Please provide example datasets where more room is needed.


https://user-images.githubusercontent.com/4214172/110396282-c025df80-803d-11eb-8085-7d763e304eb8.mp4

**Comment by BryonLewis** [comment]
making some but not perfect progress on this.
Have some panning which maintains that 10% of the images/video needs to remain on the screen but allows panning at all zoom levels.  There are some weird things that I need to iron out with it though (The bouncing on up/down/left, for some reason to the right seems to be solid).

https://user-images.githubusercontent.com/61746913/111306155-3c1bbb00-862e-11eb-92df-b590e5d62641.mp4

**Comment by BryonLewis** [comment]
Not sure how much better this is going to get without some significant diving into the GeoJS stuff.

**Comment by subdavis** [comment]
I'd personally like to consider :wontfix: for this.  We should probably just embrace the default behaviors of the tools we're using unless customers specifically need this to change.

**Comment by BryonLewis** [comment]
Backlogging this for now given a non-trivial way to implement given the geoJS setup.

**Comment by BryonLewis** [comment]
closing do to lack of interest in pushing forward.
