### ISSUE TITLE
[BUG] [Client] Type visibility controls seem broken

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#552]
**Describe the bug**

Unchecking a type doesn't change the track visiblity.

**To Reproduce**
1. Go to https://viame.kitware.com/#/viewer/5f2ad111524be434e6812c14
2. Click on checkbox RHOMBOPLItTE... to disable type
3. Nothing changes.....

**Related data**
Is there a dataset on [viame.kitware.com](https://viame.kitware.com) that illustrates this bug well?  Please link it here.

https://viame.kitware.com/#/viewer/5f2ad111524be434e6812c14

**Expected behavior**

Track should either be hidden, or next highest type should be shown.

**Desktop (please complete the following information):**

Chrome for linux

**Additional context**

**Comment by BryonLewis** [comment]
This I think is related to the multi-confidence filter bug that I've had that in limbo for like a 2 months.  I need to update that and make sure it doesn't break anything with `vue-media-annotator` to make sure it doesn't break anything.  I can get back to testing that and making sure it works properly.

#460

**Comment by subdavis** [comment]
Fixed in #460
