### ISSUE TITLE
Improve Run Pipeline drop down ordering

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#56]
Ideally the ordering would be:

default pipelines first
default_*

generic pipelines next
generic_*

then all others in alphabetical order

Ideally it also doesn't show the .pipe extension

**Comment by BryonLewis** [comment]
@mattdawkins - pining to see if this is still relevant.  We've already remove the .pipe extension do we still want the ordering like that?  (only asking because I'm working on some other small related tasks).

**Comment by BryonLewis** [comment]
Going to close.  There is only currently one generic pipeline and putting that single item at the top and sorting the rest alphabetically seems like it could be confusing.
