### ISSUE TITLE
[FEATURE] Planning for Web Attributes to Metadata switch-over

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#575]
Planning for the web metadata switch.

Right now on desktop we have metadata.json files which include the metadata for attributes built into them.  We need to convert the web version to stop using the global `viame/attributes` endpoint and start using either the metadata in the file or an individual metadata.json file that can be used to be portable between the desktop and web versions.

First thing is to swap over the current attributes to utilizing the metadata for the folder:
- Would help to be able to do incremental updates instead of wholesale metadata updates, similar to how the track.json file upserts and delete works.
- This will require a `useAttributes` tool as a sibling to use Styling and others to load and manage the attributes data locally
- Edits to attributes through the additional system will now cause metadata updates to be queued up

Second Tasks:
- Modifying ingest of csv's and existing track.json files to automatically populate attributes.  There is some code already in the desktop version to guess the type of the attribute when loading.
- Exporting of all detections should include a metadata.json file which includes customTypeStyles as well as the attributes for import on desktop version.
- Ensure that desktop version can import metadata.json and that it won't conflict with calculated attributes.
- Enable ingestion of track.json along with metadata.json for importing the attributes and styling from the desktop or another project folder.

Final Tasks:
- Sharing dialog to be able to import another public dataset's metadata for styling/attributes with the option to import both or a single one.
- This will do a merge with the current metadata without overwriting any conflicting items.
- Sharing of metadata for attributes and styling between projects.  Where a user can navigate to another public dataset and use it as a basis for their own project's attributes and types styling.
- 
-

**Comment by BryonLewis** [comment]
At the point now of doing Exporting and Importing of metadata.json files.  We have attribute calculations on both desktop and web.

**Comment by BryonLewis** [comment]
Details on Metadata.json Exporting and importing.

- Need to Specifically exporting on a full export the attributes and the custom styling.  This will allow for transferring between desktop and web those settings.
- Desktop looks for metadata.json which will contain a structure for the attributes and styling data.
- On Web it will need to be part of the import process.  Meaning that we will support multiple .json files and that validation will have to occur on each json to see if it is properly formatted
-   I may also want to provide a way to export and import only the metadata.json.  That way there is functionality to transfer data between systems/people.  This will flow eventually into sharing metadata.json files for custom types and attributes.

**Comment by subdavis** [comment]
@BryonLewis is there something actionable here or can this be closed?

**Comment by BryonLewis** [comment]
I think this can be closed, you basically implemented it.
