### ISSUE TITLE
[FEATURE] Seek to detection should also autozoom.

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#581]
"Clicking on the detection number highlights the detection but does not jump to zooming in to this detection. It would be helpful to have the zoom to detection option through one of these methods, or another. "

While some users want this, it may confuse others who need to see full frame context.  Perhaps this should be a hotkey and bound to a track list item button, but not the default behavior.

For example: `arrow` keys select track, but `shift-arrow` selects track with zoom?

**Comment by mattdawkins** [comment]
I think this should be a user setting instead of an extra/special keypress
