### ISSUE TITLE
[FEATURE] Desktop: add ability to customize window name of interface

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#594]
Looking to change both "DIVE Annotation Interface" and the top window bar from DIVE to GOOD

**Comment by subdavis** [comment]
This has a good bit of hidden cost.   Unlike the web UI where we can allow the instance administrator to set branding information, we'd have to create a new build channel to support this (or release by hand, which sorta defeats the point of the automated release process we have).   

A whole release pipeline would need to be duplicated for GOOD, or we'd have to manually build clients for them.

Until it becomes clear that this is necessary, users of the desktop can get their client builds from https://kitware.github.io/dive/Dive-Desktop/ from our regular release channel.

**Comment by subdavis** [comment]
I'd like to :wontfix: this issue.  The amount of effort to maintain something like this is really high.

**Comment by aashish24** [comment]
I agree with your assessment @subdavis
