### ISSUE TITLE
[FEATURE] Desktop: Alternative options when loading a sequence already in the system

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#606]
Need someway not to have multiple duplicates of the same folder with different annotations, e.g. it detects when a folder is already loaded in the system and asks the user if they want to use the one already there or make a new one. By default using the existing one would be better to not have a situation like the below

![open-multipl](https://user-images.githubusercontent.com/2353972/109343690-ba5d1c80-783b-11eb-87f4-c4568be8ffcb.png)

**Comment by subdavis** [comment]
Would require coordination with #593.

In this case, again, I think a prompt is necessary.  "Import new copy or open existing" would be how I'd choose to implement this.

**Comment by mattdawkins** [comment]
Either forcing there to always be one, of if there's an option for 2 need a way to differentiate between them in the recent list as well
