### ISSUE TITLE
[FEATURE] Desktop: add ability to open image files based on glob selector

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#622]
VIEW/SEAL both have the ability to select images in a folder based on a wildcard string instead of just open the entire folder.

This is useful if a directory contains multiple imagery types (e.g. IR and EO data but the user only wants to load one), see the below:

![image](https://user-images.githubusercontent.com/2353972/110494844-f73dd480-80c1-11eb-82f0-5547b0ec741c.png)

**Comment by subdavis** [comment]
![Screenshot from 2021-03-09 11-20-04](https://user-images.githubusercontent.com/4214172/110502676-6a971480-80c9-11eb-889b-fbc1aed1dcca.png)
