### ISSUE TITLE
[BUG] Tiled Tiff Filetype rejection

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#632]
**Describe the bug**
Need to either look into or reject tiled Tiff conversions utilizing ffmpeg

**To Reproduce**
1.  Uploading tiled tiffs into the system and expecting them to convert into PNGs for displaying.
2. 

**Related data**
Job reference - https://viame.kitware.com/girder/#job/6048dfca5b1737bb9085f5eb
Data Reference - Private Folder - https://viame.kitware.com/#/folder/6048dfb95b1737bb9085f5e6

**Expected behavior**
~Either we find a way to convert properly or~ rejection of the tiled tiffs during the conversion process or before it even reaches the conversion process

**Additional context**

**Comment by subdavis** [comment]
Moved to backlog, don't think this needs to be discussed.

**Comment by waxlamp** [comment]
@BryonLewis, this issue doesn't fully describe the bug.

@subdavis, I'm not sure what you meant in your last comment: doesn't need discussion could mean, we should close this issue without fixing, or it's accepted.

Finally, is this the same as #426?

**Comment by BryonLewis** [comment]
Closing as a duplicate of #426
