### ISSUE TITLE
[BUG] Always honor DIVE_VIAME_INSTALL_PATH environment path

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#640]
If I extract the VIAME desktop installers to a directory, run dive, manually change the VIAME install path in settings then despite reloading the GUI with a new DIVE_VIAME_INSTALL_PATH it still retains the old manual setting.

(the install path probably shouldn't even be a setting when the env var is specified regardless because that's just gonna confuse users)

**Comment by subdavis** [comment]
Allowing the user to override the environment variable was the intended behavior.

If this is wrong, I agree it would be better to just lock this setting when the variable is present and show a message explaining why the setting is locked.
