### ISSUE TITLE
[BUG] Can access last frame of video using play but not seek arrows

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#641]
To reproduce:

Goto https://viame.kitware.com/#/viewer/5f7df7c0753e091a2f19338a
Click play, play until last frame, draw box on last frame,
Move back to prior frames
Use arrows to arrow over until last frame, can only access 2nd to last frame not frame with box

**Comment by subdavis** [comment]
Discussed at a recent meeting.

Imagine this is a video with 12 frames `_` down-sampled to have 4 frames `|`. 

```
| _ _ _ | _ _ _ | _ _ _ | _ _ _
```

That last marker at the end is missing, obviously.    Any frame annotated at the end will be 5 (13-15) which doesn't exist.  This is a bug, but I don't know of a good way to fix it.

1) we could be rigorous during export and make sure exported frames only happen within the real media bounds
2) we could make it so the player can never play past marker 4 (example above).

Other than that, I don't really have ideas.

**Comment by subdavis** [comment]
Option 2 from above was implemented
