### ISSUE TITLE
[FEATURE] Allow power users to add/modify pipelines

### ISSUE THREAD

**Issue by russelldj** [Kitware/dive#651]
**Is your feature request related to a problem? If so, Please describe.**
I'd like to run `utilities` -> `add_segmentation_watershed` with a parameter changed from the default. It would be nice to do this on VIAME web because this is a short experiment that would be nice to visualize in browser. However, after consulting the documentation, it doesn't seem like I can run any pipelines other than those which are provided. 

**Describe the solution you'd like**
The solution that seems most appealing to me is a mechanism which allows users to upload pipelines to the user directory and have them become visible in the `Run Pipeline` menu. 

**Describe alternatives you've considered**
* I could run this pipeline in my local VIAME build and this is likely what I'll do short term. However, setting up VIAME might not be super easy, even for a technical user. Additionally, it's visualization capabilities are quite poor and this is my main complaint.
* I could try to configure DIVE locally which would likely get me good visualization. However, trying to set up Docker locally just for this seems like a bit of a hassle.

**Additional context**
I don't think this is super critical, but could make DIVE more useful to people with a moderate technical background.

**Comment by subdavis** [comment]
This is possible now and requires documentation.

I'm going to convert this to a documentation task, and then we can evaluate whether or not it meets your needs.
