### ISSUE TITLE
[FEATURE] Some way to display author information / usage rights alongside datasets

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#654]
One group requested the ability to add a readme with annotation authorship at one point to those that are in training_data

**Comment by subdavis** [comment]
Folders support markdown descriptions.

We don't show them, but it would be pretty trivial to enable these.  

Please enumerate the datasets we need to add this to and the markdown to add.

Girder Web Components supports markdown rendering, which would be pretty easy to add.

**Comment by subdavis** [comment]
Also, you didn't mention any sort of active "Accept terms" dialog on download.

Did the group mean to ask for this?  It's a little more work.
