### ISSUE TITLE
[FEATURE] Desktop annotation import for existing datasets

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#656]
**Is your feature request related to a problem? If so, Please describe.**

For users who don't understand the behavior that annotation files should be located next to source media (or who need to swap out annotation source files after an initial import).

**Describe the solution you'd like**

Where multiple CSV files are discovered, or a CSV + JSON are discovered, or maybe even no annotations are discovered, I'm thinking about adding a dropdown for the user to pick the annotation file to load, with a file picker override so that if the wrong annotations are found or they're in another place, the user can point to them.

We also need to support adding annotations after import is complete somehow with a similar file picker, I think.  

**Describe alternatives you've considered**

**Additional context**

**Comment by mattdawkins** [comment]
I definitely recommend having an import button; having the csv be in the same folder as imagery isn't necessarily a requirement and supporting alternative structures on disk the user may want is important
