### ISSUE TITLE
[FEATURE] Allow configurable FPS and change pipeline default FPS for videos to 10hz

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#665]
For all pipeline runs, annotation FPS, etc...

**Comment by subdavis** [comment]
VIAME generates annotations at 5hz by default.  Is this going to change?  When?   This needs to be coordinated.

**Comment by mattdawkins** [comment]
Parameter to drive pipeline FPS in processing pipes

downsampler:target_frame_rate                                    5

**Comment by subdavis** [comment]
What about for training?   How does the FPS for the input detentions get supplied?
