### ISSUE TITLE
[FEATURE] Not being able to click and highlight small circles in polygons confusing

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#694]
In polygon creation and editing for existing detections I found it confusing that you couldn't click and highlight the small circles between the two larger circles. I'm assuming the large circle is an existing vertex and small circle suggestion to make a new one (and you can drag click them to make a new vertix in a new position) but maybe just clicking the small circle should make a new vertex there and highlight it or something similar? As of now it selects the nearest big circle when you try to single left click the small one.

**Comment by subdavis** [comment]
I think this is just a thing users will have to learn.  It's documented here: https://kitware.github.io/dive/Annotation-QuickStart/#polygon-annotations. I'd like to wontfix this because I don't think there's a straightforward way to change this except through GeoJS.

@BryonLewis thoughts?
