### ISSUE TITLE
[FEATURE] Ability to more easily exit from continuous detection creation mode

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#697]
It's not clear that you need to press 'esc' to get out of continuous detection creation mode, needs to say that somewhere predominately or there needs to be another method to do this that is user intuitive

**Comment by BryonLewis** [comment]
just a quick test-sample of what could potentially be in place to indicate creation modes as well as all the other modes that a user could be in.  This isn't perfect yet (it doesn't update after creation, but I think the idea is there).  This is where an escape button could be used to cancel creation mode or cancel the current editing mode as well.

https://user-images.githubusercontent.com/61746913/152044762-89ec8c10-36e2-4569-b045-9f5d9514e250.mp4
