### ISSUE TITLE
[FEATURE] Cross-video analytics output into a single summary csv

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#710]
Add the ability to select multiple videos/image sequences in a folder and get one output csv with the following properties:

1) Max-N count in the first X minutes of a sequence above threshold   (for every object type report the frame with max occurrence and it's timestamp)
or
2) Mean count for the first X minutes of a sequence above threshold  (average count / frame of every known type)

**Comment by subdavis** [comment]
Please provide an exact CSV schema or format.

**Comment by mattdawkins** [comment]
VIAME has a csv format in https://github.com/VIAME/VIAME/tree/master/examples/archive_summarization

but it's not exactly a standard, its header looks like:     # video/sequence_id, time_id, frame_id, detection_count

For reporting these max-n counts, with 1 line per video but any format is really fine as long as it contains the requisite info
