### ISSUE TITLE
[BUG] Don't download 2 videos (transcoded and original) when downloading videos

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#752]
Not too important just seems like a waste

**Comment by subdavis** [comment]
For "Everything" they're going to get both because we can't be sure which they want.  Whatever choice we make, someone will inevitably want the other video.

For the "download video" dedicated button, I agree they should only get 1.  Which do you think it should be?

**Comment by mattdawkins** [comment]
If there's any (quality, not filesize) compression in the mp4 probably the original, if no quality regression probably whichever ones's smaller but maintaining the original title; barring the above probably doesn't matter much
