### ISSUE TITLE
[BUG] Deleting all features from a track causes weird state and 500 error on save.

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#758]
**Describe the bug**
Under normal circumstances, this should not happen because the keyframe toggle isn't availble on singele-frame detections.

**To Reproduce**
1. Create a track
2. Add a second detection, making it a true track
3. Remove the keyframe
4. Remove the other keyframe
5. Try to save

Results in 500 error and a ghost-track with no features (infinite bounds)

Thanks @AlmightyYakob for pointing this out.

**Comment by subdavis** [comment]
Verify that this issue was fixed along with #765

**Comment by BryonLewis** [comment]
Yeah this wouldn't have been fixed by #765, that was related only to desktop and the express server payload size.  My guess is that we should  either disallow removing the final keyframe or properly delete the track if the user removes the only keyframe.
