### ISSUE TITLE
[BUG] Support loading VIAME-CSVs without any object types

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#766]
It's possible (and a couple people do have) VIAME-CSVs created without any object types listed in them, or types missing for some detectors, though I'm sure at import time into DIVE it would be okay to specify just Unknown or something as the type if the dive interface requires it, as long as  it doesn't crash on these types of CSVs

**Comment by subdavis** [comment]
Everything needs an object type.  `[unknown, 1.0]` is a reasonable default.

**Comment by mattdawkins** [comment]
That's fine from within dive, it's not fine from the csv parsing point of VIEW (can DIVE add unknown to ones to lines which have no type? in the parser) - a 1.0 score is probably fine though if column 8 is available in the csv that would be a better number to use (https://viame.readthedocs.io/en/latest/section_links/detection_file_conversions.html) then fall back to 1.0, though minor
