### ISSUE TITLE
[FEATURE] Checkmark when training models to indicate only use frames with groundtruth on them

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#771]
TODO: Matt D put the setting here which does this on the train side

**Comment by subdavis** [comment]
@mattdawkins can you finish filling this out?

**Comment by subdavis** [comment]
Blocked on consistent arguments for multiple pipelines.

@mattdawkins will update this issue when the requisite changes are in VIAME.

**Comment by mattdawkins** [comment]
--gt-frames-only
