### ISSUE TITLE
Advanced Image caching features

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#78]
Once complete with the initial cache and sitting there idle, it should start continuing on and loading additional frames.  This secondary buffer should be cleared at any time a user interaction starts.  This prevents idle network time from not being used while also not polluting too much of the main image buffer.

The caching system should be smart enough to append on if the current frames are loaded.
1. Go to a frame location
2. Look forward and back to see if it is already cached
3. If it is already cached expand the looking distance to prevent idle times

If the previous frames are already loaded while using the front/back ratio it should append to the list the items that should be loaded instead.

If the movement is continuous backwards (indicate that they are seeking backwards) the front back ratio should be changed and priority given to frames before the current frame.

Single frame advancement outside of playback (utilizing the keys) should force the caching to be directional as well.  If the user is holding the ‘forward’ key it should be trying to reach forward in frames, the opposite is true if the user is holding the backwards key.

A single frame jump of decent size should be like before where it grabs frames alternating between front and back just in case we don’t know where the user is going.

**Comment by waxlamp** [comment]
@BryonLewis, this sounds like it's describing a prefetching scheme more so than caching--is that right?

**Comment by BryonLewis** [comment]
Yeah.  It does some of this already, this would just be increasing some of the logic behind it.  I would mark it low or possibly closed, there haven't been complaints about the load times of image frames in the past year or so.

**Comment by waxlamp** [comment]
I vote close. If complaints arise we can re-open it, or just file a new issue around the particulars at that time.
