### ISSUE TITLE
[FEATURE] Ability to move datasets around

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#790]
Hit this in the workflow demo today

**Comment by subdavis** [comment]
There's basically no chance we'll be able to do something like this with the existing UI.

I'd like to WontFix this.

**Comment by waxlamp** [comment]
@subdavis, is this solvable in spirit by opening the Girder interface and doing the data moving there?

If so, that's a way to get this done. But I agree that repeating core Girder3 features in the DIVE interface is out of scope.
