### ISSUE TITLE
[BUG] Detection <=> frame alignment issues at several different FPS

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#806]
E.g. on:

https://viame.kitware.com/#/viewer/60a664ad38c806b910e56d3c

The detections are being displayed at a different frame rate then they were computed at

**Comment by mattdawkins** [comment]
The one I linked is due to the scallop pipes not having downsamplers in them so DIVE is just taking the full frame rate annotations and ignoring the tail (I'm gonna add in downsamplers)

**Comment by subdavis** [comment]
Sounds like this isn't a bug in DIVE.  Can we close this issue?

**Comment by mattdawkins** [comment]
Closed it though it might make sense to check the output of pipes and make sure you're not getting lots of detections beyond the end of video which you would get here (it was also ignoring the timestamps in the csvs and instead just relying on frame numbers only)
