### ISSUE TITLE
[FEATURE] Option to disable annotation generation

### ISSUE THREAD

**Issue by aashish24** [Kitware/dive#819]
**Is your feature request related to a problem? If so, Please describe.**
This feature is mostly for reviewers / managers 

**Describe the solution you'd like**
We need an explicit "view-only" mode that hides all the edit GUI elements.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by aashish24** [comment]
I have looked for similar issues but did not find any and thus creating this issue which originally came from Roddy.

**Comment by subdavis** [comment]
This is basically #727
