### ISSUE TITLE
[FEATURE]  Annotation File Verification

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#829]
**Is your feature request related to a problem? If so, Please describe.**
Import and loading of CSV/JSON files should be validated instead of just blanked if invaldi.
**Describe the solution you'd like**
Web endpoint for validation of JSON file before finalizing the import and overwriting the current data.

**Comment by subdavis** [comment]
IMO, this does not need to be a separate endpoint.  Just do the file validation inside the POST handler and 400 if validation doesn't pass.

**Comment by subdavis** [comment]
This was done in #910 

https://github.com/Kitware/dive/blame/main/server/dive_server/crud.py#L243

I guess we didn't notice that it also closed this issue.
