### ISSUE TITLE
[BUG] Search bar broken on filenames with extensions

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#839]
I think this use to work but when I search for EXAMPLE_TEST_VIDEO.mp4 it is not showing the video in question, but when I search for just EXAMPLE_TEST_VIDEO it is

**Comment by subdavis** [comment]
This is the difference between full text search and search by prefix.  Prefix search would return the result you wanted, but full text does not.  These are girder/girder implementation details and are not related to code in this repository.
