### ISSUE TITLE
[FEATURE] When uploading image sequence to web version ability to select folder

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#841]
Selecting a folder of images would be a nice option in addition to having to highlight all images in a folder (and less button clicks) when selecting image sequence

**Comment by waxlamp** [comment]
Unfortunately I don't think it's possible to "upload a folder" from the browser--multiselect for individual files is as far as we can go. If I'm wrong about this, someone can correct me (and re-open this issue).
