### ISSUE TITLE
[FEATURE] Ability to select camera in multi-camera dataset.

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#851]
TODO fill out context for this issue.

Follow up to #803 

# Acceptance criteria

* Dropdown to select camera implementation.
* Discussion document for necessary features of multiple camera view.

## Possible next steps

* side-by-side view with no viewer interactions between the two cams (lots of caveats do doing something like this)

**Comment by subdavis** [comment]
Do we think we could come up with requirements for true multi-camera view as part of this issue?  Who would do that?

**Comment by BryonLewis** [comment]
Some reminders for myself about how this should work:

- Currently Stereo/MultiCam datasets have a format of `/datasetId/cameraId/` where each cameraId can be it's own dataset.
- When loading `metadata` and we have multiCam info we need to create a new UI element that can be used to toggle bewteen cameras.  When the user toggles between the cameras it will send a signal back up to the viewerLoader to change the currently display datasetId to include the camera path as well. 
- The base root datasetId will show the default camera and will also be the camera which is used to run multiCam pipelines.  When looking at individual cameras you can run other pipelines on those individual cameras.
- If I remember properly the import annotation button was a precursor to allowing this switch between cameras to happen, it has the method for reloading the dataset
- If I remember properly Viewer.vue loading will have to be modified to interpret the current camera.
- The pipelines need to automatically change their state based on swapping between them.
- Double check the following list to make sure everything works:
    - Loading, importing, saving chagnes
    - Running pipelines and the return data properly going to right location
    - Ensure training is disabled on multicam/stereo displays
    - Double check the stereo/multimedia pipelines run and return the proper results
    - Exporting of individual cameras (media, annotation, all)>
