### ISSUE TITLE
[FEATURE] Have displayed frame numbers start from 1 not 0, users just don't understand 0

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#856]

**Comment by subdavis** [comment]
I don't think I agree with this feature request.

In the output file, frame numbers begin with `0`.  Showing a different number in the interface would be significantly more confusing than telling people "start with 0".

I would really like to avoid having inconsistencies between interface and data files.

**Comment by mattdawkins** [comment]
I can see the arguments for both we've had them over and over again in vision through the years, vpview settled on 1 display in the GUI even though format started at 0

(it's a good point, regrettably making them start at 0 in the csv is one of my biggest regrets w.r.t. it) - minor issue regardless
