### ISSUE TITLE
[FEATURE] Embed new file format parser for NIST file format

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#862]
Please add requirements on this issue @collinsr

**Comment by subdavis** [comment]
Is there a data format for individual videos, or will the data always be a single file that describes annotations for multiple videos?

https://docs.google.com/document/d/15y_zHdULdBZYI_dFPQ_yu7w25KaPBqiH72YlRRy2_CU/edit is related

**Comment by collinsr** [comment]
The output we're getting from individual videos seems to be close to, but not exactly,  the schema in NIST's documentation at https://actev.nist.gov/pub/Phase3_ActEV_2021_SDL_EvaluationPlan_20210730.pdf -- I have a query out to NIST to see if this is expected, or if I'm looking in the wrong place, etc...

I've attached a sample single-video output file of the type we'd expect to get. I think it's fine to throw an exception if the user submits a file with results for more than a single video.

[chunk-test-05-json.txt](https://github.com/Kitware/dive/files/6924757/chunk-test-05-json.txt)

**Comment by collinsr** [comment]
aha -- I was misusing jq to examine the json; it is compliant with table 4 in the evaluation plan. Corrected sample attached.
[chunk-test-05-json.txt](https://github.com/Kitware/dive/files/6924831/chunk-test-05-json.txt)

**Comment by subdavis** [comment]
"Can throw an exception if the multi-video format actually contains more than one video"

**Comment by BryonLewis** [comment]
Adding these here from other documents:
https://github.com/usnistgov/ActEV_Scorer/blob/master/lib/protocols/actev_sdl_v2_schema.json

**Comment by BryonLewis** [comment]
@collinsr - A couple of questions/comments:

- The link to the PDF doesn't work it just reloads this current page
- I have that other NIST converter that has the concept of `ObjectTypes` and `ObjectIds` for bbox annotations, should this converter support those as well?

**Comment by collinsr** [comment]
Sorry -- the correct link is https://actev.nist.gov/pub/Phase3_ActEV_2021_SDL_EvaluationPlan_20210803.pdf (at least as of the writing of this comment.) I've updated the link in the above comment as well.

Yes, the two types of output we're getting (temporal and spatial) are both instances of the same schema; the "temporal-only" simply leaves out the objects.
