### ISSUE TITLE
[BUG] Minor: DIVE and KWIVER looking at different image is horizontal / vertical fields

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#866]
https://viame.kitware.com/#/viewer/6102f532c660db235f29edcd

detections computed on horizontal version in kwiver, dive shows vertical

gimp opens up image horizontally like kwiver sees it, ubuntu default image editor loads in vertically

**Comment by BryonLewis** [comment]
exif orientation data say for it to rotate.  There is a setting in GIMP you might have used at some point and then clicked the "don't ask me again" checkmark.

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage#notes

Browser should use the orientation information to orient the image automatically.

**Comment by subdavis** [comment]
Can we close this?  I think DIVE is behaving correctly.

**Comment by BryonLewis** [comment]
Closing issue, dive is using the proper orientation.
