### ISSUE TITLE
[BUG] frame alignment on videos with buffer.

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#877]
To summarize:

There are videos where the time requested for frames between the mp4 file passed to training/pipelines and inside of kwiver is different than what is displayed from the browser.

Example:
A video with a frame rate of 59.94Hz when annotated at 1Hz there is an issue in the browser where the first 3 frame ticks will display the same frame.  This isn't true for all videos created with ffmpeg but some videos that are converted will have this behavior.

**Comment by BryonLewis** [comment]
One new option I just thought of is after transcoding, doing an additional ffprobe pass where if the beginning time has multiple references to the first timestamp it will then do a `-ss 0` second pass to realign the time?

**Comment by BryonLewis** [comment]
I wrote a test script that goes through a directory/sub directories and analyzes the ffprobe results from the following command:
`f"ffprobe '{results[i]}' -hide_banner -read_intervals %+1 -show_entries frame=best_effort_timestamp_time,pkt_dts_time,pkt_pts_time,pkt_duration_time -of json > '{tempJSON.name}'"`
This only grabs the first 1 second of frames, should probably increase it to like 5 seconds for low frame rates.
This command seems to have frame alignment issues if either the frame numbers at the beginning are duplicated 0 time stamps or if the duration of the times between frames aren't even.

Result of running the script on my Download directory which has 39 videos.  The Error Files are ones with misaligned frames and they are all the same video or versions of the test video that had issues.

![Selection_266](https://user-images.githubusercontent.com/61746913/129564820-25a2a444-1ff8-4e63-b4d4-33791c5d0609.png)

To clear this up I can run it through another transcoding processing with `-ss 0` and that should fix it.

So the process for transcoding videos might change slightly:

1. Begin standard transcoding
2. Check ffprobe results for misaligned frame times or variable packet duration
3. Do a second transcoding where we reset the time to `-ss 0` to clean up misaligned frames while preserving audio
4. do a second check to see if that resolved the issue
5. If issue is resolved returned the second video file as the transcoded version
6. If the issue isn't resolved error out while providing a message to the user about while there was a problem transcoding the video and that they should contact an admin
