### ISSUE TITLE
[FEATURE] Unifying task.py temporary directory creation

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#905]
Want to solidify why we are using tempfile.TemporaryDirectory() vs tempfile.mkdtemp() there are very small differences (TemporaryDirectory() will auto remove after context is loss).

Should update task.py to have consistency or note why there are differences.

**Comment by subdavis** [comment]
Even though it would be the larger change, I think we should try to use context managers only and do away with cleanup functions.  Error handling with the cleanup function is becoming unweildy, and I found another situation where cleanup is not called on job cancellation today.

Context managers gracefully handle exceptions and you don't have to think about how it works.

What do you think?
