### ISSUE TITLE
[FEATURE] Remove recursive downloading from Pipline Runs

### ISSUE THREAD

**Issue by BryonLewis** [Kitware/dive#906]
There are endpoints for downloading CSVs and downloading media so I think that recursiveDownloading of the folder and filtering afterwards no longer needs to be used.  This should simplify some of the logic within these tasks.

**Comment by subdavis** [comment]
@BryonLewis is this issue still relevent?  

In `run_pipeline` I see:

```python
    # Download source media
    input_folder: GirderModel = gc.getFolder(input_folder_id)
    input_media_list = download_source_media(gc, input_folder_id, input_path)
```

I only see `downloadFolderRecursive` used to fetch the folder that contains model(s) if the pipeline run is for a trained model.

**Comment by BryonLewis** [comment]
I think this can be closed now because of the latest update.
