### ISSUE TITLE
[FEATURE] Ability to download multiple folders of data at once or folder of folders

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#925]
Downloaded folders would ideally also be compatible with VIAME project train structure which can accept data in any number of ways (examples below though we may be able to add other structures to train tool if difficult)

root folder
--sequence1_folder
----image1.png
----image2.png
----annotations.csv   (annotations in folder)
--sequence2_folder
----image1.png
----image2.png
--sequence2_folder.csv  (annotations outside of folder at root level same name)
--video1.avi
--video1.csv  (annotations for video, same name)
--great_folder
----video2.avi  (video in subfolder)
----video2.csv

**Comment by waxlamp** [comment]
@BryonLewis how well is this solved by the zip export feature recently added?

**Comment by BryonCLewis** [comment]
The recent zip feature was an **import** feature to take the existing dataset exports and re-import them into the server as well as zips that contain multiple folders or flat lists of images.  So the Import system should work with a similar style structure that Matt has listed.

We would have to change how de do exports to be able to support downloading multiple datasets into a single zip.  This I believe isn't allowed in the UI when multiple datasets are checked.
