### ISSUE TITLE
[FEATURE] re-use transcoded video for multiple annotation sets

### ISSUE THREAD

**Issue by collinsr** [Kitware/dive#929]
For the IARPA PM site visit, we're displaying four different annotation sets (two ground-truth, two algorithms) on the same video (for six videos); this requires uploading and transcoding the video four times. (Plus 4x the storage.)

It would be great to have a variation of "clone" which allows you to re-use the video with a new annotation set.

**Comment by subdavis** [comment]
I think what you're asking for is already possible with "Clone" and "import".

# Steps

* Upload a video
* Make a clone of the video.
* On the clone, Use the "Import" button (top right) to swap the cloned annotations for whatever you upload (CSV/Json).  

This is how the ASAPS data works: there's a folder full of the raw video, and then each of the annotaiton tasks is just a clone of the video, so each video is only uploaded once.

It should not be necessary to upload a video more than once for any use case I can think of.  Does this solve your issue?

**Comment by collinsr** [comment]
Aha-- I tried "clone" but not the "import" step. I will assume this workflow works and will reopen if it doesn't. Thanks!
