### ISSUE TITLE
[BUG] When changing the bounding box appearance, line thickness is not saved

### ISSUE THREAD

**Issue by collinsr** [Kitware/dive#932]
**Describe the bug**
When changing bounding box appearance, line thickness is not saved. Color and opacity are saved.

**To Reproduce**
Click on the event box editor.
Change color, opacity, and line thickness.
Save and exit.
Reload the project.
Color and opacity are preserved, but not thickness.

**Expected behavior**
Ideally the line thickness would be saved.

**Comment by subdavis** [comment]
I cannot reproduce.  Please confirm that you press save after setting the style.

![Screenshot from 2021-09-17 09-13-39](https://user-images.githubusercontent.com/4214172/133788483-af2695da-78ef-4ce1-8703-e79a66958546.png)

I'm going to close, but feel free to reopen if you've pressed save and don't see the thickness persisting.

**Comment by collinsr** [comment]
Aha--- I was setting the width to zero (which gives a pleasing effect for non-opaque ground-truth boxes vs. outline-only performer detections). That does not get saved. Values > 0 (I tried 1) seem to get saved.

**Comment by waxlamp** [comment]
@collinsr, would you want a mechanism to *toggle* the bounding box? Or would that lead to confusing usage?

**Comment by collinsr** [comment]
That could also work, if that's easier than allowing zero to be a valid persistent width.
