### ISSUE TITLE
[BUG] Read Only Mode is broken

### ISSUE THREAD

**Issue by subdavis** [Kitware/dive#937]
**Describe the bug**

On desktop, read-only mode no longer works

**To Reproduce**
1. Enable RO mode and save
2. Launch a dataset
4. Save button still works?

**Comment by BryonLewis** [comment]
Totally my fault: https://github.com/Kitware/dive/pull/869/files#diff-d055870fb1af3c3a41c32a582af35a97814e62fa0320f482bd71e5d749172537R63
I changed a v-bind of {readonlyMode} to `read-only-mode` when it should be `readonly-mode`
