### ISSUE TITLE
[FEATURE] DIVE-Desktop in jobs panel option to open up results in annotation

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#940]
In web on the jobs panel you can directly go from the jobs list to the annotation viewer for a sequence, though not desktop

**Comment by BryonLewis** [comment]
since it was quick, how do we feel about: 
![image](https://user-images.githubusercontent.com/61746913/134678910-9a2691b9-2f05-4e03-9f68-17c6e7980b68.png)

Would this work where the list of datasets (list because of training jobs) is clickable and can be used to open the specific data-item

**Comment by subdavis** [comment]
Can you switch the left padding to right padding so the left vertical lines up.

I like this.

**Comment by BryonLewis** [comment]
Thanks, I'll adjust the padding.  I know it isn't in the sprint and it was added afterwards, I was working on related stuff and it was a quick add to my existing branch to I put it in.
