### ISSUE TITLE
[BUG] Web Server Deployment Keeping Some Old Pipelines

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#948]
The pipeline “tracker_mouss.pipe” was removed from being in the release docker containers (as of a week ago), but it is still present on viame.kitware.com (which might be confusing to a user because this pipeline is old and deprecated vs newer tracker_mouss_deep7_v1 and v2, so the first could run by accident).

**Comment by subdavis** [comment]
When pipelines change, either in addons or in the base image, you have to let us know so we can run the update.

This has been done now.
