### ISSUE TITLE
[FEATURE] Accept VIAME Training Outputs with Tracker or Multiple Pipelines

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#949]
Training configs may produce trained_detector.pipe, trained_tracker.pipe, embedded_detector.pipe, embedded_tracker.pipe. The trained_* versions can be used by viame-web although the embedded_* ones should be ignored and not run (will indefinitely halt if using command line tool). A trained_tracker.pipe may or may not be produced depending on the train configuration. Examples forthcoming.

**Comment by subdavis** [comment]
Currently blocked on getting training config that produces more than one pipeline.

**Comment by waxlamp** [comment]
ping @mattdawkins ^^^

**Comment by BryonLewis** [comment]
Just  some confirmation here:

- reject `embedded_*` pipes from appearing in the user trained list
- Add a `{folderName} {'detector' || 'tracker'}` for each trained_detector.pipe and trained_tracker.pipe in the list
- There will never be an empty or broken `trained_tracker.pipe` in the folder?  Meaning do I have to check to make sure the pipe valid has something inside of it?
- Ensure that calling the detector produces detections and calling the tracker produces tracks
