### ISSUE TITLE
[FEATURE] Desktop advanced option where deletion in DIVE deletes original images/videos on disk

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#955]
This would need to be a non-default advanced option (maybe a CLI option that needs to be manually specified). I don't actually have a customer need / request for this just for a personal project so low priority.

**Comment by subdavis** [comment]
I don't understand the request.  Deletion in DIVE Desktop _does_ delete files.

**Comment by mattdawkins** [comment]
images and original annotations as well, this would be comboed with https://github.com/Kitware/dive/issues/954 (which I do actually have a project need for) to manage the imagery on disk through DIVE

**Comment by subdavis** [comment]
It's too complicated to support recycle bin operations cross-platform, and it's not really possible to inform a user about what they're about to delete.  If someone deletes something by accident, they could become frustrated and blame DIVE for losing all their data. This is too dangerous to implement, and I'd like to wontfix.

We could potentially support some kind of bulk delete via command line (re #954), but anything in the UI is, IMO, too much of a liability.
