### ISSUE TITLE
[BUG] Screen became orange upon pipeline completion (web)

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#956]
Orange (minor issue and changing to new helped)

![Screenshot from 2021-09-28 22-41-29](https://user-images.githubusercontent.com/2353972/135197987-2030bae4-d084-4120-b2f0-878a8e89f49b.png)

**Comment by BryonLewis** [comment]
this looks like text highlighting using the mouse where a portion of the screen was selected.

**Comment by subdavis** [comment]
Cannot reproduce on Firefox for linux.  Feel free to reopen with bug report template (version information and steps to reproduce).
