### ISSUE TITLE
[BUG] Import of json with segmentations yields negative bytes size in girder

### ISSUE THREAD

**Issue by mattdawkins** [Kitware/dive#957]
See clones in below, ala

https://viame.kitware.com/#/folder/5e4d81c5bec258fa08d8bb25

![Screenshot from 2021-09-28 23-23-56](https://user-images.githubusercontent.com/2353972/135198063-cf0afdaf-0638-4fac-a17a-35bbf032ff6f.png)

**Comment by subdavis** [comment]
Known bug in https://github.com/girder/girder

https://github.com/girder/girder/issues/3351

**Comment by subdavis** [comment]
I ran size repairs that appear to have fixed this issue.
