### ISSUE TITLE
[BUG] On web GUI, spurious "failed to delete dataset" dialog when deleting dataset

### ISSUE THREAD

**Issue by collinsr** [Kitware/dive#969]
**Describe the bug**
On viame.kitware.com, deleting a dataset generates a "failed to delete dataset" dialog. However, on refreshing the web page, the dataset seems to be deleted.

**To Reproduce**
Create a dataset; delete; confirm; observe error; refresh; dataset seems to be deleted.

**Additional context**
Screen recording attached.

https://user-images.githubusercontent.com/7387940/135692075-dc86e743-ed09-4927-911c-583984696f5a.mp4

**Comment by subdavis** [comment]
Duplicate of #961
